### PR TITLE
convertToWrapped expects a bytestring

### PR DESCRIPTION
**Pull request by Humbedooh**
Additionally, be more specific in our format=flowed search

### CODE REVIEW

**Comment by sebbASF** [comment]
-1, as this changes the  source used for hash generation. This will break most of the existing generators.

If it is desired to apply the reformatting, it needs to be done *after* the MID calculation.

However note that in my experiments, the reformatting causes badly wrapped output.

**Comment by Humbedooh** [comment]
Would it be better to look into rolling our own converter? The codebase looks very simple.

**Comment by Humbedooh** [comment]
or perhaps the formatflowed.decode() option is better suited instead of convertToWrapped...

**Comment by sebbASF** [comment]
I think we need to gather some test cases.

There are quite a few instances of format=flowed in the unit test corpus file users_httpd_apache_org_2020-07.mbox, however they don't seem to be the sort of messages that need to be wrapped.

Note: I got better results by specifying ' wrap_fixed=False' on the above corpus.

**Comment by sebbASF** [comment]
I found a few cases where the first convertToWrapped call actually worked.
So I think the solution is to leave the current code exactly as is so id generation is not affected.

Once the id has been calculated, the body can be reformatted as necessary for storage in the database.

**Pull request closed without merging**
