### PR TITLE
edit-list: handle config consistently

### PR DESCRIPTION
**Pull request by dimidd**
Read the config file regardless of what dir the script was called.

Signed-off-by: Dimid Duchovny <dimidd@gmail.com>

### CODE REVIEW

**Comment by Humbedooh** [comment]
I'm generally in favor of this change, but it may be breaking existing behavior, so it should at the very least be noted in the changelog that this is a potential breaking change.

**Comment by dimidd** [comment]
Perhaps to prevent breaking existing code we can check if the PWD has `ponymail.cfg` and perefer it over the one in the `tools` dir.

**Comment by sebbASF** [comment]
Agreed: only check tools/ if cannot find config in PWD. 
I don't see how that can break anything except a test that expects to fail because it cannot find the file.

**Comment by Humbedooh** [comment]
I think that's a very good compromise :)

**Comment by sebbASF** [comment]
I've had a look at how the other tools behave.

Currently, archiver.py and import-mbox.py both read ponymail.cfg from the parent directory.
Whereas the other tools/ scripts read from the CWD.

I think the current situation is confusing: I would expect all the tools to behave the same way.

So although this will change the behaviour, I now think it might be best for all the tools to work the same as archiver and import-mbox.

**Comment by dimidd** [comment]
Then perhaps we should abstract it into its own module?

2018-05-14 13:04 GMT+03:00 sebbASF <notifications@github.com>:

**Comment by sebbASF** [comment]
elastic.py was an attempt to extract some of the common processing into a separate module.
However perhaps it should be split further.

**Comment by sebbASF** [comment]
As I wrote previously, I don't think it makes sense to default to using the config file from the current directory. Whilst perhaps convenient for testing, it is confusing to have multiple potential sources.

I think all scripts should use the config in tools/ to ensure consistency.

**Comment by dimidd** [comment]
OK, then this PR is redundant.

**Pull request closed without merging**
